version: "3.9"

services:
  sri:               
    image: redis:7
    container_name: redis-server
    networks:
      - my-network

  client:                
    image: redis:7
    container_name: redis-client
    depends_on:
      - sri
    command: ["sleep", "infinity"]
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
